[package]
name = "war_score"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.5.1"
redis = "0.27.2"
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.128"
