[package]
name = "war_score"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.9.0"
log = "0.4.22"
redis = "0.27.6"
serde = { version = "1.0.214", features = ["derive"] }
serde_json = "1.0.134"
