version: '3.8'
services:
  statsoverlay:
    container_name: war_overlay
    image: war_overlay
    ports:
      - "55991:55991/tcp"
    volumes:
      - /home/ujr/prv/mk.db:/app/mk.db
    restart: unless-stopped
