version: '3.8'
services:
  war_overlay:
    container_name: war_overlay
    image: war_overlay
    # ports:
    #   - "25991:25991/tcp"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.waroverlay.rule=Host(`waroverlay.prismillon.com`)"
      - "traefik.http.services.waroverlay.loadbalancer.server.port=25991"
    networks:
      - proxy
    volumes:
      - /home/ujr/prv/mk.db:/app/mk.db:ro
    restart: unless-stopped

networks:
  proxy:
    external: true