version: '3.8'
services:
  war_overlay:
    container_name: war_overlay
    image: war_overlay
    ports:
      - "25991:25991/tcp"
    volumes:
      - /home/ujr/prv/mk.db:/app/mk.db
    restart: unless-stopped
